# Generated by Django 5.2 on 2025-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightfixture',
            name='channel',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lightfixture',
            name='color',
            field=models.CharField(blank=True, default='#0066cc', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='lightfixture',
            name='dimmer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lightfixture',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lightfixture',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
