# Generated by Django 5.2 on 2025-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_lightfixture_channel_lightfixture_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightingplot',
            name='addressing_system',
            field=models.CharField(choices=[('unified', 'Unified Fixture Numbers'), ('families', 'Channel/Spot Families')], default='unified', help_text='How fixtures are addressed in this plot', max_length=10),
        ),
    ]
