# Generated by Django 5.2 on 2025-05-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_lightingplot_addressing_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightfixture',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveField(
            model_name='lightfixture',
            name='fixture_type',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element_type', models.CharField(help_text='Type of elements this category contains (fixture, pipe, etc.)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which this category should be displayed')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='designer.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['element_type', 'order', 'name'],
                'unique_together': {('name', 'parent', 'element_type')},
            },
        ),
        migrations.AddField(
            model_name='lightfixture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='designer.category'),
        ),
    ]
