# Generated by Django 5.2 on 2025-05-03 19:49

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('designer', 'Category')
    LightFixture = apps.get_model('designer', 'LightFixture')
    
    # Create root category for fixtures
    root = Category.objects.create(
        name='Lighting Fixtures',
        element_type='fixture',
        description='All lighting fixtures'
    )
    
    # Create default subcategories
    conventional = Category.objects.create(
        name='Conventional',
        parent=root,
        element_type='fixture',
        description='Traditional lighting fixtures'
    )
    
    led = Category.objects.create(
        name='LED',
        parent=root,
        element_type='fixture',
        description='LED-based lighting fixtures'
    )
    
    moving = Category.objects.create(
        name='Moving Light',
        parent=root,
        element_type='fixture',
        description='Moving head and mirror fixtures'
    )
    
    effect = Category.objects.create(
        name='Effect',
        parent=root,
        element_type='fixture',
        description='Special effects fixtures'
    )
    
    # Create subcategories for conventional fixtures
    Category.objects.create(
        name='PAR',
        parent=conventional,
        element_type='fixture',
        description='Parabolic Aluminized Reflector fixtures'
    )
    
    Category.objects.create(
        name='Fresnel',
        parent=conventional,
        element_type='fixture',
        description='Fresnel lens fixtures'
    )
    
    Category.objects.create(
        name='ERS',
        parent=conventional,
        element_type='fixture',
        description='Ellipsoidal Reflector Spotlights'
    )
    
    # Update existing fixtures to use conventional category by default
    LightFixture.objects.filter(category__isnull=True).update(category=conventional)

def reverse_default_categories(apps, schema_editor):
    Category = apps.get_model('designer', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_alter_lightfixture_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
